[package]
name = "bevy_bug_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1" }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main" }